### ISSUE TITLE
Issue during torsion restrains with nitriles

### ISSUE THREAD

**Issue by jacekkozuch** [TinkerTools/poltype2#24]
Hi, 

I'm experiencing an issue during the xtb-opt step of torsion fitting due to an aromatic nitrile group in my molecule. The log file says:

**Comment by jacekkozuch** [comment]
Hi,

Not sure if there was a bug fix already, but the linearity in the torsion still seems to create issues.

**Comment by leucinw** [comment]
Hi Jacek,
I just pushed a fix for this issue. Can you try to see if it fixes your problem? Thanks
https://github.com/TinkerTools/poltype2/commit/9a456e14e573b4972a860fd6a06377a8bc7a43fa

**Comment by jacekkozuch** [comment]
> Hi Jacek, I just pushed a fix for this issue. Can you try to see if it fixes your problem? Thanks [8672f98](https://github.com/TinkerTools/poltype2/commit/8672f98ed4777605b33e284875cb31fee60b6d9f)

Dear Chengwen,

thanks for looking into it a providing a bug fix. I finally managed to get back to this and check if the problems are solved. Unfortunately, there's still an issue and it looks slightly different:

poltype.log:
`Sun Jul  2 16:55:02 2023 Traceback (most recent call last):
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 8038, in RunPoltype
    poltype.main()
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 3610, in main
    params= self.GenerateParameters()
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 4952, in GenerateParameters
    torgen.gen_torsion(self,optmol,self.torsionrestraint,mol)
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/torsiongenerator.py", line 1171, in gen_torsion
    CheckIfQMOptReachedTargetDihedral(poltype,cartxyz,initialtinkerstructure,torset,optmol,variabletorlist,phaseangles) # QM usually freezes dof but xtb and ANI does not freeze so need to add check now.
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/torsiongenerator.py", line 761, in CheckIfQMOptReachedTargetDihedral
    matches = rdkitmol.GetSubstructMatches(pattern)
AttributeError: 'NoneType' object has no attribute 'GetSubstructMatches'

Sun Jul  2 16:55:03 2023 Traceback (most recent call last):
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 8038, in RunPoltype
    poltype.main()
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 3610, in main
    params= self.GenerateParameters()
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/poltype.py", line 4952, in GenerateParameters
    torgen.gen_torsion(self,optmol,self.torsionrestraint,mol)
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/torsiongenerator.py", line 1171, in gen_torsion
    CheckIfQMOptReachedTargetDihedral(poltype,cartxyz,initialtinkerstructure,torset,optmol,variabletorlist,phaseangles) # QM usually freezes dof but xtb and ANI does not freeze so need to add check now.
  File "/home/jkozuch/poltype2_bugfix/PoltypeModules/torsiongenerator.py", line 761, in CheckIfQMOptReachedTargetDihedral
    matches = rdkitmol.GetSubstructMatches(pattern)
AttributeError: 'NoneType' object has no attribute 'GetSubstructMatches'

Sun Jul  2 16:55:03 2023 Poltype has crashed!
`

Fortunately, there's no mention of the dihedral involving the CN, so that's good now. About the rest, I checked if there's a new script to build the environment in conda, but that's still the same. Therefore, it has to be somehting specific to the molecule. Do you still have the zip that I uploaded some time ago?

Thanks a lot for looking into this!
Best,
Jacek

**Comment by leucinw** [comment]
It seems your input sdf file is somehow can not read by RDKit. What I did was to convert the file with `obabel x.sdf -O y.sdf` then everything worked fine. Of course, I turned on `debugmode` so I could use the cheapest QM settings for everything and quickly identify the issue. I suggest you re-run your job from the newly generated sdf file with the latest poltype. Let me know if you still see the error. Thanks.

**Comment by jacekkozuch** [comment]
Hi Chengwen,

thanks a lot this worked! I think there was a time when partial double bonds worked, so I didn't think about getting rid of them. 

One comment: removing partial double bonds but using "generateextendedconf=True" may turn amide bonds from trans to cis, when the extended conformation is chosen. That's maybe something that would be worth restraining by detecting amides within Poltype2.

Best,
Jacek
